### ISSUE TITLE
Too eager search

### ISSUE THREAD

**Issue by jkiddo** [bartdecu/fhirfederator#31]
When a query to the federater is eg. `Coverage?identifier=urn:oid:1.2.3.4|67890`
-it ends up doing https://github.com/bartdecu/fhirfederator/blob/4f7d432634e729c556636eeaeaded834be98fdc0/src/main/java/ca/uhn/fhir/federator/ast/AndNode.java#L36

-which tries to fetch ALL resources. IMHO it shouldn't. It should query for all resources with the same set of parameters, here being `identifier=urn:oid:1.2.3.4|67890`

**Comment by bdc-ehealth** [comment]
Hi @jkiddo ,

I cannot reproduce what you are saying:

``
21:21:47.972 INFO  c.u.f.f.FederatedSearchProvider s 
  a
    f Coverage
  ?
  c
    p
      k
        e identifier
      =
      d
        v
          w urn:oid:1.2.3.4|67890

21:21:47.975 INFO  c.u.f.f.FederatedSearchProvider Coverage?identifier=urn:oid:1.2.3.4|67890
21:21:47.987 INFO  c.u.fhir.federator.ParameterExecutor Client request Url: https://blaze.life.uni-leipzig.de/fhir/Coverage?identifier=urn:oid:1.2.3.4|67890
21:21:47.987 INFO  c.u.fhir.federator.ParameterExecutor Client request Url: https://server.fire.ly/R4/Coverage?identifier=urn:oid:1.2.3.4|67890
21:21:47.988 INFO  c.u.fhir.federator.ParameterExecutor Client request Url: https://hapi.fhir.org/baseR4/Coverage?identifier=urn:oid:1.2.3.4|67890
21:21:48.167 INFO  c.u.fhir.federator.ParameterExecutor Client request Url: https://server.fire.ly/R4/Coverage?identifier=urn:oid:1.2.3.4|67890 #0
21:21:49.439 INFO  c.u.fhir.federator.ParameterExecutor Client request Url: https://blaze.life.uni-leipzig.de/fhir/Coverage?identifier=urn:oid:1.2.3.4|67890 #0
21:21:51.075 INFO  c.u.fhir.federator.ParameterExecutor Client request Url: https://hapi.fhir.org/baseR4/Coverage?identifier=urn:oid:1.2.3.4|67890 #0
``

**Comment by jkiddo** [comment]
I see the following:
````
22:08:21.131 ERROR c.u.f.federator.FederatorInterceptor doFederation2
22:08:21.139 INFO  c.u.f.f.FederatedSearchProvider Received call with content type null and 0 bytes
22:08:21.198 INFO  c.u.f.f.FederatedSearchProvider s 
  a 
    f Coverage
  ?
  c 
    p 
      k 
        e identifier
      =
      d 
        v 
          w urn:oid:1.2.3|123

22:08:21.198 INFO  c.u.f.f.FederatedSearchProvider Coverage?identifier=urn:oid:1.2.3|123
22:08:21.214 INFO  c.u.fhir.federator.ParameterExecutor Client request Url: http://localhost:8081/Coverage
````

using the configuration of:

```
server:
  port: 8181
federator:
  members:
    - url: "http://localhost:8081"
    - url: "http://localhost:8082"
    - url: "https://hapi.fhir.org/baseR4"
  resources:
    default:
      - server: "http://localhost:8081"
      - server: "http://localhost:8082"
    other:
      Coverage:
        - server: "http://localhost:8081"
      metadata:
        - server: "https://hapi.fhir.org/baseR4"
  setup:
    url: "https://hapi.fhir.org/baseR4"
```

**Comment by jkiddo** [comment]
So why arent the parameter transferred in my case?

**Comment by bdc-ehealth** [comment]
I changed my config in this way:
```
federator:
  members:
    - url: "https://server.fire.ly/R4"
    - url: "https://blaze.life.uni-leipzig.de/fhir"
    - url: "https://hapi.fhir.org/baseR4"
    - url: "http://localhost:8081"
  resources:
    default: 
      - server: "https://server.fire.ly/R4"
      - server: "https://blaze.life.uni-leipzig.de/fhir"
      - server: "https://hapi.fhir.org/baseR4"
    other:  
      Coverage:
        - server: "http://localhost:8081"
```
and still getting the expected behaviour:
```
07:19:07.575 INFO  c.u.f.f.FederatedSearchProvider s
  a
    f Coverage
  ?
  c
    p
      k
        e identifier
      =
      d
        v
          w urn:oid:1.2.3|123

07:19:07.577 INFO  c.u.f.f.FederatedSearchProvider Coverage?identifier=urn:oid:1.2.3|123
07:19:07.578 INFO  c.u.fhir.federator.ParameterExecutor Client request Url: http://localhost:8081/Coverage?identifier=urn:oid:1.2.3|123
07:19:07.583 ERROR c.u.fhir.federator.ParameterExecutor Request failed: http://localhost:8081/Coverage?identifier=urn:oid:1.2.3|123 HAPI-1361: Failed to parse response from server when performing GET to URL http://localhost:8081/Coverage?identifier=urn%3Aoid%3A1.2.3%7C123 - org.apache.http.conn.HttpHostConnectException: Connect to localhost:8081 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: no further information
07:19:07.584 INFO  c.u.fhir.federator.ParameterExecutor Client request Url: http://localhost:8081/Coverage?identifier=urn:oid:1.2.3|123 #0
```
As you can see, I had no server running on that port.

**Comment by bdc-ehealth** [comment]
The issue reminds me of the case in which a parameter is ignored if its key is not recognized (I implemented this behaviour for your last bugreport #30 ). Are you sure your URL is properly encoded, especially the key of the parameter?

**Comment by jkiddo** [comment]
I'll double check later today and let you know 👍

**Comment by jkiddo** [comment]
Okay - I think I found out why. I imagine that your `federator.setup.url` points to `https://server.fire.ly/R4`. The Firely server exposes standard search params in both the capabilitystatement on /meta and on the SearchParameter endpoint - eg. `https://server.fire.ly/R4/SearchParameter?url=http://hl7.org/fhir/SearchParameter/Coverage-identifier` returns the standard searchparameter for Coverage.identifier. HAPI, however, has a different behaviour. Supported search parameters are on /meta but (usually) only custom search parameters are exposed on the SearchParameter endpoint - for instance, https://hapi.fhir.org/baseR4/SearchParameter?url=http://hl7.org/fhir/SearchParameter/Coverage-identifier does not return any SearchParameter resource. I believe this is the reason why I have seen the behaviour. 

If you run with the following configuration:

````
federator:
  members:
    - url: "https://server.fire.ly/R4"
    - url: "https://blaze.life.uni-leipzig.de/fhir"
    - url: "https://hapi.fhir.org/baseR4"
    - url: "http://localhost:8081"
  resources:
    default:
      - server: "https://server.fire.ly/R4"
      - server: "https://blaze.life.uni-leipzig.de/fhir"
      - server: "https://hapi.fhir.org/baseR4"
    other:
      Coverage:
        - server: "http://localhost:8081"
  setup:
    url: "https://hapi.fhir.org/baseR4"
````

and execute the following: `curl 'http://localhost:8080/fhir/Coverage?identifier=urn:oid:1.2.3%7C123'` you'll see the behaviour that I saw
